// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-6pnM3OPG7gD_HRDwS7OjWfsPRtiOypM',
    appId: '1:366050829439:web:4b15a83d5c3f14efbccb4a',
    messagingSenderId: '366050829439',
    projectId: 'ujjufire',
    authDomain: 'ujjufire.firebaseapp.com',
    databaseURL: 'https://ujjufire-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ujjufire.appspot.com',
    measurementId: 'G-K2WDYTLHRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfg8ODQEktE7cpC4h6ytJiWno8_N8RhxE',
    appId: '1:366050829439:android:32323c48b9957b8abccb4a',
    messagingSenderId: '366050829439',
    projectId: 'ujjufire',
    databaseURL: 'https://ujjufire-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ujjufire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp6TFLOhjL8Wps_vYpbAvE5DMZDOYmL9w',
    appId: '1:366050829439:ios:0f18696c556c43d7bccb4a',
    messagingSenderId: '366050829439',
    projectId: 'ujjufire',
    databaseURL: 'https://ujjufire-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ujjufire.appspot.com',
    iosBundleId: 'com.example.wedding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp6TFLOhjL8Wps_vYpbAvE5DMZDOYmL9w',
    appId: '1:366050829439:ios:0f18696c556c43d7bccb4a',
    messagingSenderId: '366050829439',
    projectId: 'ujjufire',
    databaseURL: 'https://ujjufire-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ujjufire.appspot.com',
    iosBundleId: 'com.example.wedding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-6pnM3OPG7gD_HRDwS7OjWfsPRtiOypM',
    appId: '1:366050829439:web:b85a5acffe663d6dbccb4a',
    messagingSenderId: '366050829439',
    projectId: 'ujjufire',
    authDomain: 'ujjufire.firebaseapp.com',
    databaseURL: 'https://ujjufire-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ujjufire.appspot.com',
    measurementId: 'G-XWQ7JJN0HD',
  );
}
